package cl.solemne.modelos;
// Generated 16-oct-2017 21:15:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Combos generated by hbm2java
 */
public class Combos extends Modelo implements java.io.Serializable {


     private int id;
     private Date fechaInicio;
     private Date fechaTermino;
     private String nombre;
     private Set<DetalleCombo> detalleCombos = new HashSet<DetalleCombo>(0);

    public Combos() {
    }

	
    public Combos(int id, Date fechaInicio, Date fechaTermino, String nombre) {
        this.id = id;
        this.fechaInicio = fechaInicio;
        this.fechaTermino = fechaTermino;
        this.nombre = nombre;
    }
    public Combos(int id, Date fechaInicio, Date fechaTermino, String nombre, Set<DetalleCombo> detalleCombos) {
       this.id = id;
       this.fechaInicio = fechaInicio;
       this.fechaTermino = fechaTermino;
       this.nombre = nombre;
       this.detalleCombos = detalleCombos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaTermino() {
        return this.fechaTermino;
    }
    
    public void setFechaTermino(Date fechaTermino) {
        this.fechaTermino = fechaTermino;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<DetalleCombo> getDetalleCombos() {
        return this.detalleCombos;
    }
    
    public void setDetalleCombos(Set<DetalleCombo> detalleCombos) {
        this.detalleCombos = detalleCombos;
    }




}


