package cl.solemne.modelos;
// Generated 16-oct-2017 21:15:19 by Hibernate Tools 4.3.1



/**
 * DetalleCombo generated by hbm2java
 */
public class DetalleCombo extends Modelo implements java.io.Serializable {


     private DetalleComboId id;
     private Combos combos;
     private Producto producto;

    public DetalleCombo() {
    }

    public DetalleCombo(DetalleComboId id, Combos combos, Producto producto) {
       this.id = id;
       this.combos = combos;
       this.producto = producto;
    }
   
    public DetalleComboId getId() {
        return this.id;
    }
    
    public void setId(DetalleComboId id) {
        this.id = id;
    }
    public Combos getCombos() {
        return this.combos;
    }
    
    public void setCombos(Combos combos) {
        this.combos = combos;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }




}


