package cl.solemne.modelos;
// Generated 16-oct-2017 21:15:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenCompra generated by hbm2java
 */
public class OrdenCompra extends Modelo implements java.io.Serializable {


     private int id;
     private Proveedor proveedor;
     private Date fecha;
     private Set<DetalleOCompra> detalleOCompras = new HashSet<DetalleOCompra>(0);

    public OrdenCompra() {
    }

	
    public OrdenCompra(int id, Proveedor proveedor, Date fecha) {
        this.id = id;
        this.proveedor = proveedor;
        this.fecha = fecha;
    }
    public OrdenCompra(int id, Proveedor proveedor, Date fecha, Set<DetalleOCompra> detalleOCompras) {
       this.id = id;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.detalleOCompras = detalleOCompras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<DetalleOCompra> getDetalleOCompras() {
        return this.detalleOCompras;
    }
    
    public void setDetalleOCompras(Set<DetalleOCompra> detalleOCompras) {
        this.detalleOCompras = detalleOCompras;
    }




}


