package cl.solemne.modelos;
// Generated 16-oct-2017 21:15:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto extends Modelo implements java.io.Serializable {


     private int id;
     private String nombre;
     private int valor;
     private String familia;
     private Set<DetalleCombo> detalleCombos = new HashSet<DetalleCombo>(0);
     private Set<DetalleVenta> detalleVentas = new HashSet<DetalleVenta>(0);
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<DetalleOCompra> detalleOCompras = new HashSet<DetalleOCompra>(0);

    public Producto() {
    }

	
    public Producto(int id, String nombre, int valor) {
        this.id = id;
        this.nombre = nombre;
        this.valor = valor;
    }
    public Producto(int id, String nombre, int valor, String familia, Set<DetalleCombo> detalleCombos, Set<DetalleVenta> detalleVentas, Set<Stock> stocks, Set<DetalleOCompra> detalleOCompras) {
       this.id = id;
       this.nombre = nombre;
       this.valor = valor;
       this.familia = familia;
       this.detalleCombos = detalleCombos;
       this.detalleVentas = detalleVentas;
       this.stocks = stocks;
       this.detalleOCompras = detalleOCompras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public String getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(String familia) {
        this.familia = familia;
    }
    public Set<DetalleCombo> getDetalleCombos() {
        return this.detalleCombos;
    }
    
    public void setDetalleCombos(Set<DetalleCombo> detalleCombos) {
        this.detalleCombos = detalleCombos;
    }
    public Set<DetalleVenta> getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set<DetalleVenta> detalleVentas) {
        this.detalleVentas = detalleVentas;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<DetalleOCompra> getDetalleOCompras() {
        return this.detalleOCompras;
    }
    
    public void setDetalleOCompras(Set<DetalleOCompra> detalleOCompras) {
        this.detalleOCompras = detalleOCompras;
    }




}


