package cl.solemne.modelos;
// Generated 16-oct-2017 21:15:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor extends Modelo implements java.io.Serializable {


     private int id;
     private String nombre;
     private String correo;
     private String telefono;
     private String descripcion;
     private Set<OrdenCompra> ordenCompras = new HashSet<OrdenCompra>(0);

    public Proveedor() {
    }

	
    public Proveedor(int id, String nombre, String correo, String telefono, String descripcion) {
        this.id = id;
        this.nombre = nombre;
        this.correo = correo;
        this.telefono = telefono;
        this.descripcion = descripcion;
    }
    public Proveedor(int id, String nombre, String correo, String telefono, String descripcion, Set<OrdenCompra> ordenCompras) {
       this.id = id;
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.descripcion = descripcion;
       this.ordenCompras = ordenCompras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<OrdenCompra> getOrdenCompras() {
        return this.ordenCompras;
    }
    
    public void setOrdenCompras(Set<OrdenCompra> ordenCompras) {
        this.ordenCompras = ordenCompras;
    }




}


