package cl.solemne.modelos;
// Generated 16-oct-2017 21:15:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private String rol;
     private String nombre;
     private String correo;
     private String telefono;
     private Set<Ventas> ventases = new HashSet<Ventas>(0);

    public Usuarios() {
    }

	
    public Usuarios(int id, String rol, String nombre, String correo, String telefono) {
        this.id = id;
        this.rol = rol;
        this.nombre = nombre;
        this.correo = correo;
        this.telefono = telefono;
    }
    public Usuarios(int id, String rol, String nombre, String correo, String telefono, Set<Ventas> ventases) {
       this.id = id;
       this.rol = rol;
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.ventases = ventases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }




}


